"""Example datasets, so the first thing you run needs no data of your own.

:func:`load_example` returns a ready :class:`~albireo.data.Dataset` — continuum-normalized,
with inverse variances and masks already set — plus a dictionary describing where it came
from and what was done to it.

One example ships inside the wheel and needs no network, no astropy, and no archive
account. That is deliberate: the quickstart has to work offline, in a fresh Colab notebook,
and in CI, and the fastest way to lose a new user is to make their first command a
download. Larger examples are fetched on demand from a public archive and cached under
``$ALBIREO_DATA_DIR`` (or the platform cache directory), verified against a recorded SHA-256
so a truncated download fails loudly instead of producing a subtly wrong spectrum.

Nothing here uses astropy: the cached files are ``.npz``, so :func:`numpy.load` is the whole
reader. Reading *FITS* needs astropy, but that is :mod:`albireo.io`'s job, and a user
learning the package should not have to install anything to see it work.
"""

from __future__ import annotations

import hashlib
import json
import os
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from albireo.data import Dataset, EpochData

__all__ = [
    "clear_example_cache",
    "example_info",
    "example_names",
    "load_example",
]

_USER_AGENT = "albireo example-data fetcher (+https://github.com/tjayasinghe/albireo)"
_PACKAGED_DIR = Path(__file__).parent / "data_files"


@dataclass(frozen=True)
class _Example:
    """One example dataset: where it lives, how big it is, and what it is."""

    name: str
    description: str
    packaged: bool
    filename: str
    citation: str
    url: str | None = None
    sha256: str | None = None
    n_bytes: int | None = None


_EXAMPLES: dict[str, _Example] = {
    "sb2_sim": _Example(
        name="sb2_sim",
        description=(
            "A simulated double-lined binary: 12 epochs of a P = 6 d circular SB2 on one "
            "instrument, S/N 80, with the injected truth included. Ships with the package; "
            "no download."
        ),
        packaged=True,
        filename="sb2_sim.npz",
        citation="Generated by albireo's own simulator; see scripts/build_example_datasets.py.",
    ),
}


def example_names() -> list[str]:
    """The names :func:`load_example` accepts."""
    return sorted(_EXAMPLES)


def example_info(name: str) -> dict:
    """What an example contains, where it comes from, and whether it needs a download."""
    example = _lookup(name)
    return {
        "name": example.name,
        "description": example.description,
        "packaged": example.packaged,
        "citation": example.citation,
        "url": example.url,
        "size_bytes": example.n_bytes,
        "cached": example.packaged or _cache_path(example).is_file(),
    }


def _lookup(name: str) -> _Example:
    try:
        return _EXAMPLES[name]
    except KeyError:
        raise ValueError(
            f"unknown example {name!r}. Available: {', '.join(example_names())}."
        ) from None


def load_example(name: str = "sb2_sim", *, with_truth: bool = False, progress: bool = True):
    """Load a bundled or cached example dataset.

    Parameters
    ----------
    name
        One of :func:`example_names`. The default, ``"sb2_sim"``, is packaged with albireo
        and never touches the network.
    with_truth
        Also return the injected truth, for simulated examples: the component deviation
        spectra, the orbital elements, and the light fractions used to generate the data.
        Raises for an observed dataset, where there is no truth to return.
    progress
        Print download progress for examples that are not yet cached.

    Returns
    -------
    Dataset, or (Dataset, dict)
        The dataset, plus the truth dictionary when ``with_truth`` is set. Every example
        also carries its provenance: ``dataset.metadata`` is not a thing, so read
        :func:`example_info` for that.

    Examples
    --------
    >>> import albireo as ab
    >>> dataset = ab.load_example()            # doctest: +SKIP
    >>> print(dataset.summary())               # doctest: +SKIP
    """
    example = _lookup(name)
    path = _PACKAGED_DIR / example.filename if example.packaged else _fetch(example, progress)
    dataset, truth = _read_npz(path)
    if not with_truth:
        return dataset
    if truth is None:
        raise ValueError(
            f"example {name!r} is observed data, so there is no injected truth to return. "
            "Call load_example(with_truth=False)."
        )
    return dataset, truth


def _read_npz(path: Path):
    with np.load(path, allow_pickle=False) as data:
        header = json.loads(str(data["__albireo_example__"]))
        epochs = []
        for i in range(header["n_epochs"]):
            meta = header["epochs"][i]
            epochs.append(
                EpochData(
                    wave=data[f"wave/{i}"],
                    flux=data[f"flux/{i}"],
                    ivar=data[f"ivar/{i}"],
                    bjd=float(meta["bjd"]),
                    v_bary=float(meta["v_bary"]),
                    instrument=str(meta["instrument"]),
                )
            )
        dataset = Dataset(epochs, frame=header["frame"])

        truth = None
        if header.get("has_truth"):
            truth = {
                "components": data["truth/components"],
                "light_fractions": data["truth/light_fractions"],
                "velocities": data["truth/velocities"],
                **header["truth_scalars"],
            }
    return dataset, truth


# ---------------------------------------------------------------------------
# cache
# ---------------------------------------------------------------------------


def cache_dir() -> Path:
    """Where downloaded examples are kept.

    ``$ALBIREO_DATA_DIR`` wins if it is set. Otherwise the platform convention:
    ``%LOCALAPPDATA%\\albireo\\Cache`` on Windows, ``~/Library/Caches/albireo`` on macOS,
    and ``$XDG_CACHE_HOME/albireo`` (default ``~/.cache/albireo``) elsewhere.
    """
    override = os.environ.get("ALBIREO_DATA_DIR")
    if override:
        return Path(override).expanduser()
    if sys.platform == "win32":
        base = os.environ.get("LOCALAPPDATA") or (Path.home() / "AppData" / "Local")
        return Path(base) / "albireo" / "Cache"
    if sys.platform == "darwin":
        return Path.home() / "Library" / "Caches" / "albireo"
    base = os.environ.get("XDG_CACHE_HOME") or (Path.home() / ".cache")
    return Path(base) / "albireo"


def _cache_path(example: _Example) -> Path:
    return cache_dir() / "examples" / example.filename


def clear_example_cache(name: str | None = None) -> list[Path]:
    """Delete cached example downloads; returns the paths removed.

    Packaged examples are part of the installation and are never touched. Use this if a
    download was interrupted in a way the checksum did not catch, or to reclaim the space.
    """
    targets = [_lookup(name)] if name else list(_EXAMPLES.values())
    removed = []
    for example in targets:
        if example.packaged:
            continue
        path = _cache_path(example)
        if path.is_file():
            path.unlink()
            removed.append(path)
    return removed


def _fetch(example: _Example, progress: bool) -> Path:
    path = _cache_path(example)
    if path.is_file() and _sha256(path) == example.sha256:
        return path

    if example.url is None:  # pragma: no cover - registry bug, not a user error
        raise RuntimeError(f"example {example.name!r} has no download URL recorded")

    path.parent.mkdir(parents=True, exist_ok=True)
    if progress:
        size = f" ({example.n_bytes / 1e6:.1f} MB)" if example.n_bytes else ""
        print(f"albireo: downloading example {example.name!r}{size} to {path.parent}")

    # Written to a .part file and moved into place only after the checksum passes, so an
    # interrupted download can never be mistaken for a cached one.
    tmp = path.with_name(path.name + ".part")
    _download_with_retries(example.url, tmp)

    digest = _sha256(tmp)
    if example.sha256 and digest != example.sha256:
        tmp.unlink(missing_ok=True)
        raise RuntimeError(
            f"downloaded example {example.name!r} has SHA-256 {digest}, expected "
            f"{example.sha256}. The download was corrupted, or the hosted file changed; "
            "please open an issue."
        )
    tmp.replace(path)
    return path


def _download_with_retries(url: str, destination: Path, attempts: int = 4) -> None:
    """Fetch ``url`` to ``destination``, retrying transient failures with backoff."""
    transient = (urllib.error.URLError, TimeoutError, ConnectionError, OSError)
    delay = 2.0
    last: Exception | None = None
    for attempt in range(1, attempts + 1):
        try:
            request = urllib.request.Request(url, headers={"User-Agent": _USER_AGENT})
            with (
                urllib.request.urlopen(request, timeout=120.0) as response,
                destination.open("wb") as handle,
            ):
                while chunk := response.read(1 << 20):
                    handle.write(chunk)
            return
        except urllib.error.HTTPError as exc:
            # A 404 or a 403 will not fix itself; only rate limits and server errors are
            # worth waiting out.
            if exc.code != 429 and exc.code < 500:
                destination.unlink(missing_ok=True)
                raise
            last = exc
        except transient as exc:
            last = exc
        if attempt == attempts:
            destination.unlink(missing_ok=True)
            raise RuntimeError(f"downloading {url} failed after {attempts} attempts: {last!r}")
        print(f"  retry {attempt}/{attempts - 1}: {last}", file=sys.stderr)
        time.sleep(delay)
        delay *= 2


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1 << 20):
            digest.update(chunk)
    return digest.hexdigest()
