"""Example datasets for running albireo without supplying data.

:func:`load_example` returns a ready :class:`~albireo.data.Dataset` (continuum-normalized,
with inverse variances and masks already set) and, on request, the injected truth for a
simulated example. :func:`example_info` reports the provenance of each entry.

One example, ``sb2_sim``, ships inside the wheel and requires no network access, no
astropy and no archive account. Larger examples are fetched on demand from a public
archive and cached under ``$ALBIREO_DATA_DIR``, or under the platform cache directory
(:func:`cache_dir`). Each cached file is verified against a recorded SHA-256 digest and is
moved into place only after the digest matches, so a truncated or altered download is
rejected rather than read as a spectrum.

The cached files are ``.npz`` and are read with :func:`numpy.load`, so this module has no
astropy dependency; reading FITS is the job of :mod:`albireo.io`.
"""

from __future__ import annotations

import hashlib
import json
import os
import sys
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from albireo.data import Dataset, EpochData

__all__ = [
    "clear_example_cache",
    "example_info",
    "example_names",
    "load_example",
]

_USER_AGENT = "albireo example-data fetcher (+https://github.com/tjayasinghe/albireo)"
_PACKAGED_DIR = Path(__file__).parent / "data_files"


@dataclass(frozen=True)
class _Example:
    """Registry entry for one example dataset: its location, size, contents and citation."""

    name: str
    description: str
    packaged: bool
    filename: str
    citation: str
    url: str | None = None
    sha256: str | None = None
    n_bytes: int | None = None


_EXAMPLES: dict[str, _Example] = {
    "sb2_sim": _Example(
        name="sb2_sim",
        description=(
            "A simulated double-lined binary: 12 epochs of a P = 6 d, e = 0.15 SB2 on one "
            "instrument, S/N 80, with the injected truth included. Ships with the package; "
            "no download."
        ),
        packaged=True,
        filename="sb2_sim.npz",
        citation="Generated by albireo's own simulator; see scripts/build_example_datasets.py.",
    ),
}


def example_names() -> list[str]:
    """The names :func:`load_example` accepts."""
    return sorted(_EXAMPLES)


def example_info(name: str) -> dict:
    """What an example contains, where it comes from, and whether it must be downloaded.

    Parameters
    ----------
    name
        One of :func:`example_names`.

    Returns
    -------
    dict
        The registry entry: ``name``, ``description``, ``packaged``, ``citation``, ``url``,
        ``size_bytes`` and ``cached``.

    Raises
    ------
    ValueError
        If ``name`` is not a registered example.
    """
    example = _lookup(name)
    return {
        "name": example.name,
        "description": example.description,
        "packaged": example.packaged,
        "citation": example.citation,
        "url": example.url,
        "size_bytes": example.n_bytes,
        "cached": example.packaged or _cache_path(example).is_file(),
    }


def _lookup(name: str) -> _Example:
    try:
        return _EXAMPLES[name]
    except KeyError:
        raise ValueError(
            f"unknown example {name!r}. Available: {', '.join(example_names())}."
        ) from None


def load_example(name: str = "sb2_sim", *, with_truth: bool = False, progress: bool = True):
    """Load a packaged or cached example dataset.

    A packaged example is read from the installation. Any other example is downloaded once
    into :func:`cache_dir`, verified against its recorded SHA-256 digest, and read from the
    cache thereafter.

    Parameters
    ----------
    name
        One of :func:`example_names`. The default, ``"sb2_sim"``, is packaged with albireo
        and requires no network access.
    with_truth
        Also return the injected truth, for simulated examples: the component deviation
        spectra, the orbital elements, and the light fractions used to generate the data.
        Raises for an observed dataset, which has no injected truth.
    progress
        Print download progress for examples that are not yet cached.

    Returns
    -------
    Dataset, or (Dataset, dict)
        The dataset, and the truth dictionary when ``with_truth`` is set. A
        :class:`~albireo.data.Dataset` carries no provenance attribute; the provenance of
        an example is reported by :func:`example_info`.

    Raises
    ------
    ValueError
        If ``name`` is not a registered example, or ``with_truth`` is requested for an
        observed dataset.

    Examples
    --------
    >>> import albireo as ab
    >>> dataset = ab.load_example()            # doctest: +SKIP
    >>> print(dataset.summary())               # doctest: +SKIP
    """
    example = _lookup(name)
    path = _PACKAGED_DIR / example.filename if example.packaged else _fetch(example, progress)
    dataset, truth = _read_npz(path)
    if not with_truth:
        return dataset
    if truth is None:
        raise ValueError(
            f"example {name!r} is observed data, so there is no injected truth to return. "
            "Call load_example(with_truth=False)."
        )
    return dataset, truth


def _read_npz(path: Path):
    with np.load(path, allow_pickle=False) as data:
        header = json.loads(str(data["__albireo_example__"]))
        epochs = []
        for i in range(header["n_epochs"]):
            meta = header["epochs"][i]
            epochs.append(
                EpochData(
                    wave=data[f"wave/{i}"],
                    flux=data[f"flux/{i}"],
                    ivar=data[f"ivar/{i}"],
                    bjd=float(meta["bjd"]),
                    v_bary=float(meta["v_bary"]),
                    instrument=str(meta["instrument"]),
                )
            )
        dataset = Dataset(tuple(epochs), frame=header["frame"])

        truth = None
        if header.get("has_truth"):
            truth = {
                "components": data["truth/components"],
                "light_fractions": data["truth/light_fractions"],
                "velocities": data["truth/velocities"],
                **header["truth_scalars"],
            }
    return dataset, truth


# ---------------------------------------------------------------------------
# cache
# ---------------------------------------------------------------------------


def cache_dir() -> Path:
    """Where downloaded examples are kept.

    ``$ALBIREO_DATA_DIR`` takes precedence when set. Otherwise the platform convention:
    ``%LOCALAPPDATA%\\albireo\\Cache`` on Windows, ``~/Library/Caches/albireo`` on macOS,
    and ``$XDG_CACHE_HOME/albireo`` (default ``~/.cache/albireo``) elsewhere.
    """
    override = os.environ.get("ALBIREO_DATA_DIR")
    if override:
        return Path(override).expanduser()
    if sys.platform == "win32":
        base = os.environ.get("LOCALAPPDATA") or (Path.home() / "AppData" / "Local")
        return Path(base) / "albireo" / "Cache"
    if sys.platform == "darwin":
        return Path.home() / "Library" / "Caches" / "albireo"
    base = os.environ.get("XDG_CACHE_HOME") or (Path.home() / ".cache")
    return Path(base) / "albireo"


def _cache_path(example: _Example) -> Path:
    return cache_dir() / "examples" / example.filename


def clear_example_cache(name: str | None = None) -> list[Path]:
    """Delete cached example downloads and return the paths removed.

    Packaged examples are part of the installation and are never removed.

    Parameters
    ----------
    name
        Clear only this example. ``None`` clears every cached example.

    Returns
    -------
    list of pathlib.Path
        The files deleted.
    """
    targets = [_lookup(name)] if name else list(_EXAMPLES.values())
    removed = []
    for example in targets:
        if example.packaged:
            continue
        path = _cache_path(example)
        if path.is_file():
            path.unlink()
            removed.append(path)
    return removed


def _fetch(example: _Example, progress: bool) -> Path:
    path = _cache_path(example)
    if path.is_file() and _sha256(path) == example.sha256:
        return path

    if example.url is None:  # pragma: no cover - registry bug, not a user error
        raise RuntimeError(f"example {example.name!r} has no download URL recorded")

    path.parent.mkdir(parents=True, exist_ok=True)
    if progress:
        size = f" ({example.n_bytes / 1e6:.1f} MB)" if example.n_bytes else ""
        print(f"albireo: downloading example {example.name!r}{size} to {path.parent}")

    # Written to a .part file and moved into place only after the digest matches, so an
    # interrupted download cannot be mistaken for a cached one.
    tmp = path.with_name(path.name + ".part")
    _download_with_retries(example.url, tmp)

    digest = _sha256(tmp)
    if example.sha256 and digest != example.sha256:
        tmp.unlink(missing_ok=True)
        raise RuntimeError(
            f"downloaded example {example.name!r} has SHA-256 {digest}, expected "
            f"{example.sha256}. The download was corrupted, or the hosted file changed; "
            "please open an issue."
        )
    tmp.replace(path)
    return path


def _download_with_retries(url: str, destination: Path, attempts: int = 4) -> None:
    """Fetch ``url`` to ``destination``, retrying transient failures with backoff."""
    transient = (urllib.error.URLError, TimeoutError, ConnectionError, OSError)
    delay = 2.0
    last: Exception | None = None
    for attempt in range(1, attempts + 1):
        try:
            request = urllib.request.Request(url, headers={"User-Agent": _USER_AGENT})
            with (
                urllib.request.urlopen(request, timeout=120.0) as response,
                destination.open("wb") as handle,
            ):
                while chunk := response.read(1 << 20):
                    handle.write(chunk)
            return
        except urllib.error.HTTPError as exc:
            # A 404 or 403 is not transient; only 429 and 5xx responses are retried.
            if exc.code != 429 and exc.code < 500:
                destination.unlink(missing_ok=True)
                raise
            last = exc
        except transient as exc:
            last = exc
        if attempt == attempts:
            destination.unlink(missing_ok=True)
            raise RuntimeError(f"downloading {url} failed after {attempts} attempts: {last!r}")
        print(f"  retry {attempt}/{attempts - 1}: {last}", file=sys.stderr)
        time.sleep(delay)
        delay *= 2


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(1 << 20):
            digest.update(chunk)
    return digest.hexdigest()
